### ISSUE TITLE
Model size & casing

### ISSUE THREAD

**Issue by ZhaofengWu** [EmilyAlsentzer/clinicalBERT#1]
Thanks for the release! Is this based on BERT base or BERT large? Also, is it the cased model or the uncased one?

**Comment by ZhaofengWu** [comment]
And have you experimented with other size & casing configurations?

**Comment by EmilyAlsentzer** [comment]
This model is based on BERT Base, and it is the cased model. We haven't experimented with BERT large or uncased models yet, but that may be available in the future.
