### ISSUE TITLE
About the pretrain Model

### ISSUE THREAD

**Issue by Billy-Zhoup** [EmilyAlsentzer/clinicalBERT#10]
Hi:
First of all, thanks for the sharing of your pretrain model : )
I'm a WPI Data Science Master student, and I'm doing an NLP internship at Umass Medical school. Your pretrain model should be very helpful for me 👍 

I have a question.
After I download the pretrain model, I found there are a set of TensorFlow model(1.2G) file and a PyTorch model file (400M).
Are they the same model?

**Comment by EmilyAlsentzer** [comment]
Glad you like clinicalBERT! Yes, they are the same model. We used Huggingface's transformer github repo to convert from the tensorflow to pytorch model.

**Comment by Billy-Zhoup** [comment]
> Glad you like clinicalBERT! Yes, they are the same model. We used Huggingface's transformer github repo to convert from the tensorflow to pytorch model.

Hi Emily, 

I still have one question.

For your model pretrained from Biobert, which version of Biobert you are using?

From biobert: https://github.com/naver/biobert-pretrained, there are 4 versions.

Thank you : )
