### ISSUE TITLE
About your Biobert pretrain model

### ISSUE THREAD

**Issue by Billy-Zhoup** [EmilyAlsentzer/clinicalBERT#11]
Hi Emily,

I still have one question.

For your model pretrained from Biobert, which version of Biobert you are using?

From biobert: https://github.com/naver/biobert-pretrained, there are 4 versions.

Thank you : )

**Comment by EmilyAlsentzer** [comment]
We used `Pre-trained weight of BioBERT v1.0 (+PubMed 200K +PMC 270K)`
