### ISSUE TITLE
Do you plan on re-training with newer BERT models such as ALBERT?

### ISSUE THREAD

**Issue by Weilin37** [EmilyAlsentzer/clinicalBERT#13]
Since ALBERT has SOTA performance + it is much smaller in model size, I was wondering if you planned on retraining based on ALBERT rather than vanilla BERT.

**Comment by EmilyAlsentzer** [comment]
Hi, Weilin. Yes, there are folks in our group who are working on extending clinical BERT to ALBERT. Stay tuned!

**Comment by MostHumble** [comment]
> Hi, Weilin. Yes, there are folks in our group who are working on extending clinical BERT to ALBERT. Stay tuned!

Hi Emiliy, any updates on this?
