### ISSUE TITLE
Support TensorFlow 2.0 or TensorFlow 1.15

### ISSUE THREAD

**Issue by maziyarpanahi** [EmilyAlsentzer/clinicalBERT#18]
Hi,

I was wondering if there is ongoing work in publishing pre-trained weights in TF 2.x or TF 1.15 (V1)? 

Many thanks,

**Comment by EmilyAlsentzer** [comment]
We recently added the clinicalBERT models to the Huggingface transformers model hub. You can use the [transformers library](https://github.com/huggingface/transformers) to switch between tensorflow 2.0 and pytorch. See the updated README for details.
