### ISSUE TITLE
Clarification on Tokenizer for MIMIC

### ISSUE THREAD

**Issue by dramacloak** [EmilyAlsentzer/clinicalBERT#20]
I don't see the BERT tokenizers utilized in the code for the MIMIC fine tuning (seems to be that these have a custom tokenizer code), and this doesn't appear to do the WordPiece tokenization used in the rest of BERT. You do appear to use the BERT-based tokenizer for the MedNLI task. Please clarify.

**Comment by EmilyAlsentzer** [comment]
We use the wordPiece tokenization from Google's BERT repo for all tokenization. The `create_pretraining_data.py` script is identical to [original script](https://github.com/google-research/bert/blob/master/create_pretraining_data.py) from the BERT repo. We currently do not include all of the imports necessary to run this script (e.g. tokenization.py) in our repo, but you can find them all in the [Google BERT repo](https://github.com/google-research/bert). 

The `heuristic_tokenize.py` script, which is perhaps poorly named, is only used to split the MIMIC notes into sections. Each note is split into sections, and each section is split into sentences using Scispacy in the script `format_mimic_for_BERT.py`.

Hope this clarifies things. Feel free to reopen the issue if you have any questions.
