### ISSUE TITLE
Two clinical BERT repos?

### ISSUE THREAD

**Issue by sudarshan85** [EmilyAlsentzer/clinicalBERT#3]
Hi,

Is this repo from the same team as [this](https://github.com/kexinhuang12345/clinicalBERT) or are they completely different?

**Comment by tnaumann** [comment]
These are two independent projects. This repository corresponds to https://arxiv.org/abs/1904.03323, which will be presented at the Clinical Natural Language Processing (ClinicalNLP) Workshop at NAACL 2019: https://clinical-nlp.github.io/2019/program.html.

The repository you linked to corresponds to https://arxiv.org/abs/1904.05342.

**Comment by sudarshan85** [comment]
Thank you for your reply. In the paper it says "For pre-training ClinicalBert, we randomly sample 100,000 notes from mimic-iii.". Does this mean that the pre-trained weights that are available for download were trained on a random sample of 100,000 notes? Or do you have a BERT trained model that is trained on all of the MIMIC notes (over 2 million)?

**Comment by sudarshan85** [comment]
Thank you for your reply. In the paper it says that you used tensorflow for your experiments. Can we use the pretrained weights with pytorch? More specifically, do the weights just correspond to the architecture which can effectively be loaded using pytorch?

**Comment by EmilyAlsentzer** [comment]
Yes, you can use the models with pytorch. We converted the models to pytorch using the code provided by the [Pytorch-Pretrained-BERT repo](https://github.com/huggingface/pytorch-pretrained-BERT). All you will need is  `pytorch_model.bin` and `bert_config.json` if you want to use pytorch.
