### ISSUE TITLE
Model not able to initalize weights

### ISSUE THREAD

**Issue by YojanaGadiya** [EmilyAlsentzer/clinicalBERT#30]
Dear all,

I am getting an initalization error about loading the model with BertforTokenClassification. Is there any way to get rid of this error?

![image](https://user-images.githubusercontent.com/45199062/94256197-b4c87700-ff29-11ea-85c6-50431d8fdfcc.png)

Thank You.

**Comment by EmilyAlsentzer** [comment]
Can you provide a bit more detail regarding what produced this message? Note that the clinicalBERT model on the Huggingface hub is not fine tuned for NER. Does loading the model as described in issue #29 work?

**Comment by YojanaGadiya** [comment]
Hey, yes I have used the model for NER using AutomodelforTokencalssification form transformers library. But I get this error.

![image](https://user-images.githubusercontent.com/45199062/94358866-3c39f580-00a4-11eb-9763-c12f285539a8.png)

I am not sure whether it affects the pre-model or not though. But in general, I would like to know whether this is normal behavior? if not, how to solve this issue?

**Comment by EmilyAlsentzer** [comment]
This behavior is expected because the clinical BERT model on the huggingface repo was only trained on the MLM and next sentence prediction tasks. If you want to use the model for NER, you need to fine-tune the model on your own data.
