### ISSUE TITLE
Instaling dependnices

### ISSUE THREAD

**Issue by TahaAslani** [EmilyAlsentzer/clinicalBERT#35]
I am trying to installing the dependencies by running
`conda create --name <env> --file requirements.txt`
However, since I don't have many of the required channels, my conda cannot install all of them. Moreover, my conda also cannot file the pip packages (pypi_0) from my current channels, even though I have pip. Can you please provide the .yml file of your environment, which contains the full description of the environment, including the conda channels?
Thanks!

**Comment by TahaAslani** [comment]
Could you please also mention how did you install spacy and scispacy? And how en_core_sci_md was downloaded?
This is how I installed them:
pip install spacy==2.0.18
pip install scispacy==0.1.0
pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_md-0.4.0.tar.gz

**Comment by EmilyAlsentzer** [comment]
Apologies for the huge delay! Yes, that should work.

**Comment by TahaAslani** [comment]
Thanks!
