### ISSUE TITLE
404 client error trying to access via Hugging Face

### ISSUE THREAD

**Issue by NicoleJaneway** [EmilyAlsentzer/clinicalBERT#36]
404 Client Error: Not Found for url: https://huggingface.co/emilyalsentzer/Bio_ClinicalBERT/resolve/main/tf_model.h5

It seems like this may be related to the upgrade to [ktrain v0.26.x](https://github.com/amaiya/ktrain#news-and-announcements)?

**Comment by EmilyAlsentzer** [comment]
Hi @NicoleJaneway, is the issue that you want to use a tensorflow version of clinicalBERT, but it's not available? If so, you should be able to use the transformers library to convert between the pytorch and tensorflow versions (see e.g. [here](https://github.com/huggingface/transformers/issues/9204)). If it's something else, please give a bit more context. Thanks!

**Comment by NicoleJaneway** [comment]
Hi @EmilyAlsentzer, thanks very much for your prompt response.  What I'm learning is that I can continue to work with the app regardless of the 404 error.  There's some other issue that's preventing the app from working.  No action needed - thank you again.

**Comment by EmilyAlsentzer** [comment]
Okay, sounds good. Feel free to open another issue if you have any more questions.
