### ISSUE TITLE
Clinical BERT, initialized from BERTBase is not available

### ISSUE THREAD

**Issue by ghost** [EmilyAlsentzer/clinicalBERT#5]
Thanks for making clinical bert publicly available. In the paper, it was mentioned liked "**We train and publicly release BERT-Base and BioBERT-finetuned models trained on both all clinical notes and only discharge summaries**".

But only BioBERT finetuned models are available . I would like to know, when will you release BERT based fine tuned models?

**Comment by EmilyAlsentzer** [comment]
We've added the clinicalBERT models initialized with BERT to the repo. However, as a heads up, we found that the clinicalBERT models initialized with BioBERT tended to work better on downstream tasks.
