### ISSUE TITLE
NER on i2b2 datasets

### ISSUE THREAD

**Issue by betterzhou** [EmilyAlsentzer/clinicalBERT#6]
Hi, 
thanks for your release. It's a great work. But I still have a question.

In the paper, you mentioned 'Clinical BERT and Clinical BioBERT were applied to four i2b2 NER tasks, all in IOB format'. I want to reproduce this work. But in this repo, you do not release NER codes in 'downstream_tasks' directory. Can you share the code?
Besides, can you tell me how to convert the four i2b2 datasets into BIO format ?

**Comment by EmilyAlsentzer** [comment]
Hi @betterzhou. We can definitely share the code. I'll push to the repo in the next few days and notify you when I do so.

**Comment by betterzhou** [comment]
Great~   Hope for your sharing.

**Comment by EmilyAlsentzer** [comment]
NER code has been added. We're not able to share the i2b2 data itself due to data access restrictions, but we have shared the code we used for preprocessing into BIO format as well as the code for training and evaluating the models. Hope this helps.

**Comment by betterzhou** [comment]
Thanks for your sharing.
Best Regards
