### ISSUE TITLE
missing mli_train_v1.jsonl 

### ISSUE THREAD

**Issue by vgopinath** [EmilyAlsentzer/clinicalBERT#7]
Hi,
run_classifier.py is looking for this json file..mli_train_v1.jsonl
how to get or construct this file?

**Comment by EmilyAlsentzer** [comment]
`mli_train_v1.jsonl`, `mli_dev_v1.jsonl`, and `mli_test_v1.jsonl` are the json files containing the MedNLI data we used. To download the MedNLI data from PhysioNet, go to this site: https://www.physionet.org/content/mednli/1.0.0/. Note that you'll need a Physionet account to access the data. If you want to use another dataset besides the MedNLI data, you should replace these mentions in the code with the datasets of your choice and modify the MedNLIProcessor to read in the data accordingly.
