### ISSUE TITLE
Need python packages in run_ner.py

### ISSUE THREAD

**Issue by betterzhou** [EmilyAlsentzer/clinicalBERT#9]
Dear @EmilyAlsentzer 
Your clinicalBERT is a great work and I want to reimplement it.
The run_ner.py requires python packages, such as 'modeling', 'optimization', and 'tokenization'. 
Can you share the packages ?
Thank you

**Comment by EmilyAlsentzer** [comment]
All of those packages come from the original BERT repo: https://github.com/google-research/bert. Since we adapted this code from the kyzhouhzau/BERT-NER repo, this code is in tensorflow. Hope this helps!
